//
// Created by AleXutzZu on 21/05/2025.
//

#ifndef OOP_PROJECT_LIBRARYMANAGEMENT_PUBLICATION_H
#define OOP_PROJECT_LIBRARYMANAGEMENT_PUBLICATION_H


class Publication {

};


#endif //OOP_PROJECT_LIBRARYMANAGEMENT_PUBLICATION_H
